apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-cloud-dns-account-key
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: gcp-cloud-dns-account-key       # name of the k8s Secret to be created
  data:
  - secretKey: service-account.json
    remoteRef:
      key: initial-secret
      property: GCP_SA
