apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-secret-store
spec:
  provider:
    kubernetes:
      # with this, the store is able to pull only from `default` namespace
      remoteNamespace: default
      server:
        url: "https://kubernetes.default"
        caProvider:
          type: ConfigMap
          namespace: default
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: "ext-secret-sa"
          namespace: default
