apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.org/client-max-body-size: 200m
spec:
  tls:
    - hosts:
      - {{ .Values.domain2 }}
      secretName: minio-api-cert
  rules:
    - host: {{ .Values.domain2 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: https-minio
