apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: jenkins-secrets       # name of the k8s Secret to be created
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key:  mlflow-secrets
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key:  mlflow-secrets
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: ADS_MINIO_ACCESS_KEY
    remoteRef:
      key:  initial-secret
      property: ADS_MINIO_ACCESS_KEY
  - secretKey: ADS_MINIO_SECRET_KEY
    remoteRef:
      key:  initial-secret
      property: ADS_MINIO_SECRET_KEY
  - secretKey: jenkins-admin-user
    remoteRef:
      key:  initial-secret
      property: JENKINS_ADMIN_USERNAME
  - secretKey: jenkins-admin-password
    remoteRef:
      key:  initial-secret
      property: JENKINS_ADMIN_PASSWORD
