loki-stack:
  enabled: true
  test_pod:
    enabled: false
  promtail:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-log:3100/loki/api/v1/push
    initContainer:
      # -- Specifies whether the init container for setting inotify max user instances is to be enabled
      - name: init
        # -- Docker registry, image and tag for the init container image
        image: docker.io/busybox:1.33
        # -- Docker image pull policy for the init container image
        imagePullPolicy: IfNotPresent
        # -- The inotify max user instances to configure
        command:
          - sh
          - -c
          - sysctl -w fs.inotify.max_user_instances=1024
        securityContext:
          privileged: true
  loki:
    fullnameOverride: loki-log
    persistence:
      enabled: false
    config:
    alerting_groups: []
    extraArgs:
      server.grpc-max-recv-msg-size-bytes: "52428800" #50 MB
      server.grpc-max-send-msg-size-bytes: "52428800"

  grafana:
    enabled: true
    fullnameOverride: loki-log-grafana
    envRenderSecret: {}
    admin:
      existingSecret: "grafana-credentials"
      userKey: GRAFANA_USER
      passwordKey: GRAFANA_PASSWORD
    image:
      tag: 8.5.13
