apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jenkins
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'jenkins-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/rtaf-soc/rtarf-rke2-ml-addons.git
        targetRevision: "{{name}}" #Based on environment
        path: '03-argocd-apps/manifests/jenkins'
      destination:
        name: in-cluster
        namespace: jenkins
      syncPolicy:
        # automated:
        #   selfHeal: false
        #   prune: true
        syncOptions:
          - CreateNamespace=true
