apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio-ml
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'minio-ml-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/rtaf-soc/rtarf-rke2-ml-addons.git
        targetRevision: "{{name}}" #Based on environment
        path: '03-argocd-apps/manifests/minio-ml'
      destination:
        name: in-cluster
        namespace: minio-ml
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
