apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 4096m
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: mlflow-cert
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlflow-production
                port:
                  number: 5000
