apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-gateway
  labels:
    app: mlflow-gateway
spec:
  selector:
    matchLabels:
      app: mlflow-gateway
  template:
    metadata:
      labels:
        app: mlflow-gateway
    spec:
      containers:
        - name: mlflow-gateway
          image: gcr.io/its-artifact-commons/ml-training-gateway:master-b73ad0b #change here
          env:
            - name: gateway_port_ml
              value: "5000"                          
          # command: ["/bin/sleep", "3650d"]      
          resources:
            limits:
              cpu: 1000m
              memory: 700Mi
            requests:
              cpu: 200m
              memory: 300Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          envFrom:
          - configMapRef:
              name: gateway-cfm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-gateway
  name: mlflow-gateway
spec:
  ports:
  - name: http-web
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlflow-gateway
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mlflow-gateway
spec:
  minReplicas: 30
  maxReplicas: 40
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlflow-gateway
  targetCPUUtilizationPercentage: 60