apiVersion: v2
name: helm-cert-manager
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Cert Manager

dependencies:
  - name: cert-manager
    version: "1.8.0"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
